export const GET_OPEN_SURVEYS = "GET_OPEN_SURVEYS";
export const GET_USER_SURVEYS = "GET_USER_SURVEYS";
export const GET_FULL_SURVEY = "GET_FULL_SURVEY";
export const ADD_SURVEY = "ADD_SURVEY";
export const UPDATE_SURVEY = "UPDATE_SURVEY";
export const PUBLISH_SURVEY = "PUBLISH_SURVEY";
export const CLOSE_SURVEY = "CLOSE_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";

// section
export const SET_ACTIVE_SECTION = "SET_ACTIVE_SECTION";
export const ADD_SECTION = "ADD_SECTION";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const UPDATE_SECTION_INDEX = "UPDATE_SECTION_INDEX";
export const DELETE_SECTION = "DELETE_SECTION";

// question
export const SET_ACTIVE_QUESTION = "SET_ACTIVE_QUESTION";
export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_QUESTION_INDEX = "UPDATE_QUESTION_INDEX";
export const DELETE_QUESTION = "DELETE_QUESTION";

// response
export const GET_RESPONSES = "GET_RESPONSES";
export const GET_RESPONSE = "GET_RESPONSE";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const REMOVE_REPSONSE = "REMOVE_RESPONSE";

// response Group
export const GET_RESPONSE_GROUPS = "GET_RESPONSE_GROUPS";

// question summaries
export const GET_QUESTION_SUMMARIES = "GET_QUESTION_SUMMARIES";

export const GET_QUESTION_ADVANCE_CHARTS = "GET_QUESTION_ADVANCE_CHARTS"

// error
export const DISPATCH_ERROR = "DISPATCH_ERROR";

// attachment Objects for upload files
export const UPDATE_ATTACHMENT_OBJECTS = "UPDATE_ATTACHMENT_OBJECTS";
