export const GET_OPEN_SURVEY_LIST = "GET_OPEN_SURVEY_LIST";
export const GET_USER_SURVEY_LIST = "GET_USER_SURVEY_LIST";
export const GET_FULL_SURVEY = "GET_FULL_SURVEY";
export const ADD_SURVEY = "ADD_SURVEY";
export const UPDATE_SURVEY = "UPDATE_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";

// section
export const ADD_SECTION = "ADD_SECTION";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const UPDATE_SECTION_INDEX = "UPDATE_SECTION_INDEX";
export const DELETE_SECTION = "DELETE_SECTION";

// question
export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_QUESTION_INDEX = "UPDATE_QUESTION_INDEX";
export const DELETE_QUESTION = "DELETE_QUESTION";

// response
export const GET_RESPONSES = "GET_RESPONSES";
export const GET_RESPONSE = "GET_RESPONSE";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const REMOVE_REPSONSE = "REMOVE_RESPONSE";

// error
export const FETCH_SURVEYS_FAILED = "FETCH_SURVEYS_FAILED";

// attachment Objects for upload files
export const UPDATE_ATTACHMENT_OBJECTS = "UPDATE_ATTACHMENT_OBJECTS";
