import * as exprt from "../../shared/export";

export const SAMPLE_SURVEY_LIST = Array.from(
  { length: 10 },
  (_, i) => i
).reduce(
  (result, _, index) => [
    ...result,
    {
      [`${exprt.props.SURVEY_ID}`]: index,
      [`${exprt.props.SURVEY_NAME}`]: `surv${index}`,
      [`${exprt.props.SURVEY_TYPE}`]: "ANONYMOUS",
      [`${exprt.props.SURVEY_PUBLISHED_DATE}`]: "",
      [`${exprt.props.SURVEY_CREATED_DATE}`]: exprt.funcs.dateFormat(
        new Date()
      ),
      [`${exprt.props.SURVEY_CLOSED_DATE}`]: "",
      [`${exprt.props.SURVEY_IS_CLOSED}`]: true,
      [`${exprt.props.RESPONSE_COUNT}`]: 0,
    },
  ],
  []
);

export const SAMPLE_FULL_SURVEY = {
  id: 1,
  name: "Testing response",
  type: "ANONYMOUS",
  description: "",
  createdDate: "2020-10-06 09:22:23",
  publishDate: "2020-10-06 13:47:57",
  closeDate: "2020-10-06 10:21:59",
  closed: false,
  numberOfSections: 1,
  questionSections: [
    {
      id: 2,
      description: "",
      questions: [
        {
          questionType: "MULTIPLE_CHOICE",
          id: 4,
          description:
            '<p>Multiple choice with image</p>\n<div style="text-align:left;"><img src="blob:http://localhost:3000/5b19e353-d4bd-4b2d-8cc7-dc598c6f2fa5" alt="" style="height: 120px;width: 100px" attachmentindex="0"></div>\n<p></p>\n',
          attachments: ["http://localhost:8080/api/files/3"],
          choices: ["1", "2", "3", "4"],
          minSelections: 1,
          maxSelections: 1,
          questionIndex: 0,
        },
        {
          questionType: "MULTIPLE_CHOICE",
          id: 5,
          description: "<p>Multiple choice without image</p>\n",
          attachments: [],
          choices: ["no img 1", "no img 2", "no img 3"],
          minSelections: 1,
          maxSelections: 1,
          questionIndex: 1,
        },
        {
          questionType: "MULTIPLE_CHOICE",
          id: 6,
          description:
            "<p>Multiple choice with restrictions min = 1, max = 3</p>\n",
          attachments: [],
          choices: ["1", "2", "3"],
          minSelections: 1,
          maxSelections: 3,
          questionIndex: 2,
        },
        {
          questionType: "MULTIPLE_CHOICE",
          id: 7,
          description:
            "<p><strong>Multiple choice with restrictions min = 1, max = 2</strong></p>\n",
          attachments: [],
          choices: ["1", "2", "3"],
          minSelections: 1,
          maxSelections: 2,
          questionIndex: 3,
        },
        {
          questionType: "MULTIPLE_CHOICE",
          id: 8,
          description:
            "<p><strong>Multiple choice with restrictions min = 2, max = 3</strong></p>\n",
          attachments: [],
          choices: ["1", "2", "3", "4"],
          minSelections: 2,
          maxSelections: 3,
          questionIndex: 4,
        },
        {
          questionType: "RANKING",
          id: 9,
          description: "<p>Ranking without duplicate answer</p>\n",
          attachments: [],
          rankingChoices: ["r1", "r2", "r3"],
          questionIndex: 5,
        },
        {
          questionType: "RANKING",
          id: 10,
          description: "<p>Ranking with duplicate answer</p>\n",
          attachments: [],
          rankingChoices: ["r1", "r2", "r1", "r3", "r2"],
          questionIndex: 6,
        },
        {
          questionType: "RATING",
          id: 11,
          description: "<p>Rating question</p>\n",
          attachments: [],
          ratingScale: 7,
          questionIndex: 7,
        },
        {
          questionType: "TEXT",
          id: 12,
          description: "<p>Texting without limit length</p>\n",
          attachments: [],
          textLength: -1,
          attachmentAllowed: false,
          questionIndex: 8,
        },
        {
          questionType: "TEXT",
          id: 13,
          description: "<p>Texting with limit length</p>\n",
          attachments: [],
          textLength: 7,
          attachmentAllowed: false,
          questionIndex: 9,
        },
      ],
      sectionIndex: 0,
    },
  ],
  numberOfResponses: 10,
  // [`${exprt.props.SURVEY_ID}`]: 0,
  // [`${exprt.props.SURVEY_NAME}`]: "SAMPLE_FULL_SURVEY",
  // [`${exprt.props.SURVEY_TYPE}`]: "ANONYMOUS",
  // [`${exprt.props.SURVEY_DESCRIPTION}`]: "",

  // [`${exprt.props.SURVEY_CREATED_DATE}`]: exprt.funcs.dateFormat(new Date()),
  // [`${exprt.props.SURVEY_PUBLISHED_DATE}`]: "",
  // [`${exprt.props.SURVEY_CLOSED_DATE}`]: "",
  // [`${exprt.props.SURVEY_IS_CLOSED}`]: true,

  // [`${exprt.props.SECTION_LIST}`]: Array.from(
  //   { length: 5 },
  //   (_, i) => i
  // ).reduce(
  //   (result, _, index) => [
  //     ...result,
  //     {
  //       [`${exprt.props.SECTION_ID}`]: Math.floor(Math.random() * 100),
  //       [`${exprt.props.SECTION_NAME}`]: "",
  //       [`${exprt.props.SECTION_DESCRIPTION}`]: "",
  //       [`${exprt.props.SECTION_INDEX}`]: index,

  //       [`${exprt.props.QUESTION_LIST}`]: Array.from(
  //         { length: 5 },
  //         (_, i) => i
  //       ).reduce(
  //         (result, _, index) => [
  //           ...result,
  //           {
  //             [`${exprt.props.QUESTION_ID}`]: Math.floor(Math.random() * 100),
  //             [`${exprt.props.QUESTION_INDEX}`]: index,
  //             [`${exprt.props.QUESTION_DESCRIPTION}`]: "<p>testing description</p>",
  //             [`${exprt.props.QUESTION_ATTACHMENTS}`]: [],
  //             [`${exprt.props.QUESTION_TYPE}`]: exprt.props.MC_TYPE,
  //             [`${exprt.props.MC_ANSWERS}`]: [
  //               "ans1",
  //               "ans2",
  //               "ans3",
  //               "ans4",
  //               "ans5",
  //             ],
  //             [`${exprt.props.MC_MIN_SEL}`]: 2,
  //             [`${exprt.props.MC_MAX_SEL}`]: 2,
  //           },
  //         ],
  //         []
  //       ),
  //     },
  //   ],
  //   []
  // ),

  // [`${exprt.props.RESPONSE_LIST}`]: [],
};

export const SAMPLE_RESPONSE_LIST = [
  {
    id: 192,
    survey: 1,
    type: "ANONYMOUS",
    date: "2012-12-01 15:46:18",
    isDeleted: false,
    totalResposeGroups: 1,
  },
  {
    id: 204,
    survey: 1,
    type: "ANONYMOUS",
    date: "2015-12-01 15:47:13",
    isDeleted: false,
    totalResposeGroups: 1,
  },
  {
    id: 216,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-01 15:47:43",
    isDeleted: false,
    totalResposeGroups: 2,
  },
  {
    id: 228,
    survey: 1,
    type: "ANONYMOUS",
    date: "2012-12-01 15:48:31",
    isDeleted: false,
    totalResposeGroups: 1,
  },
  {
    id: 240,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-01 15:49:09",
    isDeleted: false,
    totalResposeGroups: 2,
  },
  {
    id: 252,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-01 15:49:37",
    isDeleted: false,
    totalResposeGroups: 2,
  },
  {
    id: 264,
    survey: 1,
    type: "ANONYMOUS",
    date: "2022-12-01 15:50:12",
    isDeleted: false,
    totalResposeGroups: 1,
  },
  {
    id: 276,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-01 15:50:43",
    isDeleted: false,
    totalResposeGroups: 3,
  },
  {
    id: 288,
    survey: 1,
    type: "ANONYMOUS",
    date: "2022-12-01 15:51:12",
    isDeleted: false,
    totalResposeGroups: 3,
  },
  {
    id: 300,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-01 15:51:47",
    isDeleted: false,
    totalResposeGroups: 2,
  },
  {
    id: 344,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-04 00:15:37",
    isDeleted: false,
    totalResposeGroups: 0,
  },
  {
    id: 356,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-04 00:16:09",
    isDeleted: false,
    totalResposeGroups: 0,
  },
  {
    id: 368,
    survey: 1,
    type: "ANONYMOUS",
    date: "2020-12-04 00:16:41",
    isDeleted: false,
    totalResposeGroups: 0,
  },
];
//   Array.from(
//   { length: 10 },
//   (_, i) => i
// ).reduce(
//   (result, _, index) => [
//     ...result,
//     {
//       [`${exprt.props.RESPONSE_ID}`]: index + 1,
//       [`${exprt.props.RESPONSE_TYPE}`]: "ANONYMOUS",
//       [`${exprt.props.RESPONSE_DATE}`]: exprt.funcs.dateFormat(new Date()),
//       [`${exprt.props.IS_ARCHIVED}`]: false,
//     },
//   ],
//   []
// );

export const SAMPLE_FULL_RESPONSE = {
  [`${exprt.props.RESPONSE_SURVEY_ID}`]: 0,
  [`${exprt.props.RESPONSE_ID}`]: 1,
  [`${exprt.props.RESPONSE_TYPE}`]: "ANONYMOUS",
  [`${exprt.props.RESPONSE_DATE}`]: exprt.funcs.dateFormat(new Date()),
  [`${exprt.props.IS_ARCHIVED}`]: false,

  [`${exprt.props.RESPONSE_SECTION_LIST}`]: Array.from(
    { length: 5 },
    (_, i) => i
  ).reduce(
    (result, _, index) => [
      ...result,
      {
        [`${exprt.props.RESPONSE_SECTION_ID}`]: index,
        [`${exprt.props.RESPONSE_SECTION_DESCRIPTION}`]: "",
        [`${exprt.props.ANSWER_LIST}`]: Array.from(
          { length: 5 },
          (_, i) => i
        ).reduce(
          (result, _, index) => [
            ...result,
            {
              [`${exprt.props.ANSWER_SECTION_ID}`]: index,
              [`${exprt.props.ANSWER_ID}`]: index + 1,
              [`${exprt.props.ANSWER_DESCRIPTION}`]: "<p>testing description</p>",
              [`${exprt.props.ANSWER_TYPE}`]: exprt.props.MC_TYPE,
              [`${exprt.props.ANSWER_MC_ANSWERS}`]: [index],

              [`${exprt.props.ANSWER_ATTACHMENTS}`]: [],
            },
          ],
          []
        ),
      },
    ],
    []
  ),
};

export const SAMPLE_QUESTION_SUMMARY = {
  2: {
    4: {
      questionType: "MULTIPLE_CHOICE",
      id: 483,
      question: 4,
      totalResponses: 13,
      selectionResponses: {
        0: {
          id: 484,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "1",
          responses: [
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        1: {
          id: 485,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "2",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        2: {
          id: 486,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "3",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
          ],
        },
        3: {
          id: 487,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "4",
          responses: [
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
      },
    },
    5: {
      questionType: "MULTIPLE_CHOICE",
      id: 488,
      question: 5,
      totalResponses: 13,
      selectionResponses: {
        0: {
          id: 489,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "no img 1",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        1: {
          id: 490,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "no img 2",
          responses: [
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        2: {
          id: 491,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "no img 3",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
      },
    },
    6: {
      questionType: "MULTIPLE_CHOICE",
      id: 492,
      question: 6,
      totalResponses: 13,
      selectionResponses: {
        0: {
          id: 493,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "1",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        1: {
          id: 494,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "2",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        2: {
          id: 495,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "3",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
      },
    },
    7: {
      questionType: "MULTIPLE_CHOICE",
      id: 496,
      question: 7,
      totalResponses: 13,
      selectionResponses: {
        0: {
          id: 497,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "1",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        1: {
          id: 498,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "2",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        2: {
          id: 499,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "3",
          responses: [
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
      },
    },
    8: {
      questionType: "MULTIPLE_CHOICE",
      id: 500,
      question: 8,
      totalResponses: 13,
      selectionResponses: {
        0: {
          id: 501,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "1",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        1: {
          id: 502,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "2",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        2: {
          id: 503,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "3",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        3: {
          id: 504,
          name: "",
          groupType: null,
          groupBy: "mulChoiceSelection",
          groupedValue: "4",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
          ],
        },
      },
    },
    9: {
      questionType: "RANKING",
      id: 505,
      question: 9,
      totalResponses: 13,
      rankingnResponses: {
        "1:0": {
          id: 506,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r1",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "1:1": {
          id: 507,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r2",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "2:0": {
          id: 508,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r1",
          responses: [
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
          ],
        },
        "1:2": {
          id: 509,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r3",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "2:1": {
          id: 510,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r2",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "3:0": {
          id: 511,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r1",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "2:2": {
          id: 512,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r3",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "3:1": {
          id: 513,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r2",
          responses: [
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "3:2": {
          id: 514,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r3",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
          ],
        },
      },
    },
    10: {
      questionType: "RANKING",
      id: 515,
      question: 10,
      totalResponses: 13,
      rankingnResponses: {
        "1:0": {
          id: 516,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r1",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
          ],
        },
        "1:1": {
          id: 517,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r2",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "2:0": {
          id: 518,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r1",
          responses: [
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "1:2": {
          id: 519,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r1",
          responses: [
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "2:1": {
          id: 520,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r2",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "3:0": {
          id: 521,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r1",
          responses: [
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "1:3": {
          id: 522,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r3",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "2:2": {
          id: 523,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r1",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "3:1": {
          id: 524,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r2",
          responses: [
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "4:0": {
          id: 525,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "4:r1",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "1:4": {
          id: 526,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "1:r2",
          responses: [
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "2:3": {
          id: 527,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r3",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "3:2": {
          id: 528,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r1",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "4:1": {
          id: 529,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "4:r2",
          responses: [
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
          ],
        },
        "5:0": {
          id: 530,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "5:r1",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
          ],
        },
        "2:4": {
          id: 531,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "2:r2",
          responses: [
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "3:3": {
          id: 532,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r3",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "4:2": {
          id: 533,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "4:r1",
          responses: [
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "5:1": {
          id: 534,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "5:r2",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "3:4": {
          id: 535,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "3:r2",
          responses: [],
        },
        "4:3": {
          id: 536,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "4:r3",
          responses: [
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "5:2": {
          id: 537,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "5:r1",
          responses: [],
        },
        "4:4": {
          id: 538,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "4:r2",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        "5:3": {
          id: 539,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "5:r3",
          responses: [
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        "5:4": {
          id: 540,
          name: "",
          groupType: null,
          groupBy: "rankOption",
          groupedValue: "5:r2",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
      },
    },
    11: {
      questionType: "RATING",
      id: 541,
      question: 11,
      totalResponses: 13,
      ratingResponses: {
        1: {
          id: 542,
          name: "",
          groupType: null,
          groupBy: "ratingOption",
          groupedValue: "1",
          responses: [
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        2: {
          id: 543,
          name: "",
          groupType: null,
          groupBy: "ratingOption",
          groupedValue: "2",
          responses: [],
        },
        3: {
          id: 544,
          name: "",
          groupType: null,
          groupBy: "ratingOption",
          groupedValue: "3",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
        4: {
          id: 545,
          name: "",
          groupType: null,
          groupBy: "ratingOption",
          groupedValue: "4",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        5: {
          id: 546,
          name: "",
          groupType: null,
          groupBy: "ratingOption",
          groupedValue: "5",
          responses: [
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        6: {
          id: 547,
          name: "",
          groupType: null,
          groupBy: "ratingOption",
          groupedValue: "6",
          responses: [
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        7: {
          id: 548,
          name: "",
          groupType: null,
          groupBy: "ratingOption",
          groupedValue: "7",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
          ],
        },
      },
      avgRating: 4.46,
      maxRating: {
        7: 1,
      },
      minRating: {
        1: 1,
      },
    },
    12: {
      questionType: "TEXT",
      id: 549,
      question: 12,
      totalResponses: 13,
      textResponses: {
        answered: {
          id: 550,
          name: "",
          groupType: null,
          groupBy: "textOption",
          groupedValue: "answered",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        skipped: {
          id: 551,
          name: "",
          groupType: null,
          groupBy: "textOption",
          groupedValue: "skipped",
          responses: [
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
          ],
        },
      },
    },
    13: {
      questionType: "TEXT",
      id: 552,
      question: 13,
      totalResponses: 13,
      textResponses: {
        answered: {
          id: 553,
          name: "",
          groupType: null,
          groupBy: "textOption",
          groupedValue: "answered",
          responses: [
            {
              id: 204,
              survey: 1,
              type: "ANONYMOUS",
              date: "2015-12-01 15:47:13",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 240,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:09",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 356,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:09",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 368,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:16:41",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
        skipped: {
          id: 554,
          name: "",
          groupType: null,
          groupBy: "textOption",
          groupedValue: "skipped",
          responses: [
            {
              id: 192,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:46:18",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 216,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:47:43",
              isDeleted: false,
              totalResposeGroups: 17,
            },
            {
              id: 228,
              survey: 1,
              type: "ANONYMOUS",
              date: "2012-12-01 15:48:31",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 252,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:49:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
            {
              id: 264,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:50:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 276,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:50:43",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 288,
              survey: 1,
              type: "ANONYMOUS",
              date: "2022-12-01 15:51:12",
              isDeleted: false,
              totalResposeGroups: 18,
            },
            {
              id: 300,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-01 15:51:47",
              isDeleted: false,
              totalResposeGroups: 21,
            },
            {
              id: 344,
              survey: 1,
              type: "ANONYMOUS",
              date: "2020-12-04 00:15:37",
              isDeleted: false,
              totalResposeGroups: 19,
            },
          ],
        },
      },
    },
  },
};

export const SAMPLE_QUESTION_SUMMARY1 = {
  16: {
    22: {
      id: 2082,
      question: 22,
      totalResponses: 1,
      selectionResponses: {
        0: {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        1: {
          responses: [],
        },
        2: {
          responses: [],
        },
      },
    },
    23: {
      id: 2086,
      question: 23,
      totalResponses: 1,
      ratingResponses: {
        1: {
          responses: [],
        },
        2: {
          responses: [],
        },
        3: {
          responses: [],
        },
        4: {
          responses: [],
        },
        5: {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        6: {
          responses: [],
        },
        7: {
          responses: [],
        },
      },
    },
    24: {
      id: 2094,
      question: 24,
      totalResponses: 1,
      textResponses: {
        answered: {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        skipped: {
          responses: [],
        },
      },
    },
  },
  17: {
    25: {
      id: 2097,
      question: 25,
      totalResponses: 1,
      rankingnResponses: {
        "1:0": {
          responses: [],
        },
        "1:1": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        "2:0": {
          responses: [],
        },
        "1:2": {
          responses: [],
        },
        "2:1": {
          responses: [],
        },
        "3:0": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        "1:3": {
          responses: [],
        },
        "2:2": {
          responses: [],
        },
        "3:1": {
          responses: [],
        },
        "4:0": {
          responses: [],
        },
        "1:4": {
          responses: [],
        },
        "2:3": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        "3:2": {
          responses: [],
        },
        "4:1": {
          responses: [],
        },
        "5:0": {
          responses: [],
        },
        "2:4": {
          responses: [],
        },
        "3:3": {
          responses: [],
        },
        "4:2": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        "5:1": {
          responses: [],
        },
        "3:4": {
          responses: [],
        },
        "4:3": {
          responses: [],
        },
        "5:2": {
          responses: [],
        },
        "4:4": {
          responses: [],
        },
        "5:3": {
          responses: [],
        },
        "5:4": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
      },
    },
    26: {
      id: 2123,
      question: 26,
      totalResponses: 1,
      textResponses: {
        answered: {
          responses: [],
        },
        skipped: {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
      },
    },
  },
  15: {
    18: {
      id: 2063,
      question: 18,
      totalResponses: 1,
      selectionResponses: {
        0: {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        1: {
          responses: [],
        },
        2: {
          responses: [],
        },
      },
    },
    19: {
      id: 2067,
      question: 19,
      totalResponses: 1,
      rankingnResponses: {
        "1:0": {
          responses: [],
        },
        "1:1": {
          responses: [],
        },
        "2:0": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        "1:2": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        "2:1": {
          responses: [],
        },
        "3:0": {
          responses: [],
        },
        "2:2": {
          responses: [],
        },
        "3:1": {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        "3:2": {
          responses: [],
        },
      },
    },
    21: {
      id: 2077,
      question: 21,
      totalResponses: 1,
      selectionResponses: {
        0: {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        1: {
          responses: [
            {
              id: 2051,
              survey: 14,
              type: "ANONYMOUS",
              date: "2020-11-09 22:30:09",
              isDeleted: false,
            },
          ],
        },
        2: {
          responses: [],
        },
        3: {
          responses: [],
        },
      },
    },
  },
};

export const SAMPLE_QUESTION_ADVANCE_CHARTS = [
  {
    id: 100,
    name: "Sample Chart",
    type: exprt.props.QUESTION_ADVANCE_CHART,
    questionId: 4,
    resGroups: [439, 440, 349, 347, 348],
  },
  {
    id: 101,
    name: "Sample Chart 1",
    type: exprt.props.QUESTION_ADVANCE_CHART,
    questionId: 4,
  },
];
